Update to minizip 1.2.13 (#515)
* Update to minizip 1.2.13

https://github.com/madler/zlib/releases/tag/v1.2.13

Noticed by building libdigidocpp 3.14.11 on OpenBSD where we still have
to pass `CFLAGS += -DIOAPI_NO_64` as off_t is always 64-bit.

1.2.13 contains a fix for this but libdigidocpp would fail to build, i.e.
it still ships an old version.

* Fix build with minizip 1.2.13

zip.h's `struct zip_fileinfo` member `tm_zip tmz_date` changed member
types from to `int`, so drop the cast as all `struct tm` members are
`int` already.

Fixes the following:
```
/usr/ports/pobj/libdigidocpp-3.14.11/libdigidocpp-3.14.11/src/util/ZipSerialize.cpp:186:11: error: non-constant-expression cannot be narrowed from type 'uInt' (aka 'unsigned int') to 'int' in initializer list [-Wc++11-narrowing]
        { uInt(time.tm_sec), uInt(time.tm_min), uInt(time.tm_hour),
          ^~~~~~~~~~~~~~~~~
/usr/ports/pobj/libdigidocpp-3.14.11/libdigidocpp-3.14.11/src/util/ZipSerialize.cpp:186:11: note: insert an explicit cast to silence this issue
        { uInt(time.tm_sec), uInt(time.tm_min), uInt(time.tm_hour),
          ^~~~~~~~~~~~~~~~~
          static_cast<int>()
```

* Fix minizip typo

Spotted by Raul Metsma during review.